import{a as v,S as q,i}from"./assets/vendor-B0XWlCgv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const M="55875706-c6fa52b10f2b0b0fddf74a165",P="https://pixabay.com/api/";async function u(r,t){return(await v.get(P,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const t=r.map(({webformatURL:a,largeImageURL:c,tags:e,likes:o,views:n,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${n}</p>
          <p><b>Comments</b> ${w}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){f.innerHTML=""}function g(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function R(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}const L=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",s=1,d=0;L.addEventListener("submit",x);O.addEventListener("click",E);async function x(r){if(r.preventDefault(),l=L.elements["search-text"].value.trim(),!l){i.warning({message:"Please enter a search query!",position:"topRight"});return}s=1,$(),b(),g();try{const t=await u(l,s);if(d=t.totalHits,t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(t.hits),d>15&&R()}catch{i.error({message:"Something went wrong!",position:"topRight"})}finally{y()}}async function E(){s+=1,g();try{const r=await u(l,s);p(r.hits),H();const t=Math.ceil(d/15);s>=t&&(b(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong!",position:"topRight"})}finally{y()}}function H(){const r=document.querySelector(".gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
