import{a as q,S as M,i as n}from"./assets/vendor-B0XWlCgv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="55875706-c6fa52b10f2b0b0fddf74a165",B="https://pixabay.com/api/";async function f(r,t){return(await q.get(B,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),R=new M(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({webformatURL:a,largeImageURL:c,tags:e,likes:o,views:s,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${s}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${v}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){h.innerHTML=""}function y(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}function L(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const w=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",i=1,u=0;w.addEventListener("submit",x);O.addEventListener("click",E);async function x(r){if(r.preventDefault(),l=w.elements["search-text"].value.trim(),!l){n.warning({message:"Please enter a search query!",position:"topRight"});return}i=1,$(),d(),y();try{const t=await f(l,i);if(u=t.totalHits,t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),u>15?L():(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong!",position:"topRight"})}finally{b()}}async function E(){i+=1,d(),y();try{const r=await f(l,i);g(r.hits),H();const t=Math.ceil(u/15);i>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{n.error({message:"Something went wrong!",position:"topRight"})}finally{b()}}function H(){const r=document.querySelector(".gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
